services:
  app:
    container_name: app-restro-assignment
    build: .
    ports:
      - "5800:8500"
    env_file:
      - .env.production
    volumes:
      - ./media:/app/media
    restart: always
